[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
petgraph = "0.6.5"
itertools = "0.13.0"
num-traits = "0.2.19"
ndarray = "0.16.1"

[dev-dependencies]
rand_chacha = "0.3.1"